name: Deploy Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalando dependências
        run: npm ci

      - name: Compilando TypeScript
        run: npm run build

      - name: Compactando função
        run: |
          mkdir -p dist
          cp package*.json dist/
          cd dist
          npm install --omit=dev
          cp -r ../build/* .
          zip -r function.zip .

      - name: Deploy para Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          inlineScript: |
            aws lambda update-function-code \
              --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
              --zip-file fileb://dist/function.zip
